---
title: New note in single page app diagram
---

sequenceDiagram

    autonumber

    Note over Browser:  Visits the website, GET method - fetch data
    Browser->>Server: https://studies.cs.helsinki.fi/exampleapp/spa

    activate Server
    Note over Server: Send: spa.html
    Server-->>Browser: .html file tells the browser what information to display and its structure
    deactivate Server

    activate Browser 
    Note over Browser: GET: main.css 
    Browser->>Server: 
    deactivate Browser 
    Note over Server: Send: main.css 
    Server-->>Browser: .css file tells the browser how to style the information

    activate Browser 
    Note over Browser: GET: spa.js 
    Browser->>Server: 
    deactivate Browser 
    Note over Server: Send: spa.js 
    Server-->>Browser: Browser runs the JavaScript code which retrieves the JSON file from server

    activate Browser 
    Note over Browser: GET: data.json 
    Browser->>Server: 
    deactivate Browser 
    Note over Server: Send: data.json
    Server-->>Browser: Browser displays the data contained in the JSON file, using an 'event handler'

    Note over Browser: User types something in the web form 
    Note right of Server: Status code: 201, petition created
    Browser->>Server: POST req: https://studies.cs.helsinki.fi/exampleapp/new_note_spa
   

    Note over Browser, Server: The client adds the data to the page dynamically, no need full page reload, then send the new data to the server to update data.json
    
    
 

