---
title: New note diagram
---


sequenceDiagram

    autonumber

    Note over Browser:  Visits the website, GET method 
    Browser->>Server: https://studies.cs.helsinki.fi/exampleapp/new_note

    activate Server
    Note over Server: Send: notes.html
    Server-->>Browser: .html file tells the browser what information to display and its structure
    deactivate Server

    activate Browser 
    Note over Browser: GET: main.css 
    Browser->>Server: 
    deactivate Browser 
    Note over Server: Send: main.css 
    Server-->>Browser: .css file tells the browser how to style the information

    activate Browser 
    Note over Browser: GET: main.js 
    Browser->>Server: 
    deactivate Browser 
    Note over Server: Send: main.js 
    Server-->>Browser: Browser runs the JavaScript code which retrieves the JSON file from server

    activate Browser 
    Note over Browser: GET: data.json 
    Browser->>Server: 
    deactivate Browser 
    Note over Server: Send: data.json
    Server-->>Browser: Browser displays the data contained in the JSON file, using an 'event handler'

    Note over Browser: User types something in the web form 
    Browser->>Server: POST req: https://studies.cs.helsinki.fi/exampleapp/new_note
    activate Server

    Note over Server: Status code: 302, tells the client to make a GET req
    Server-->>Browser: GET: https://studies.cs.helsinki.fi/exampleapp/notes
    deactivate Server

    activate Browser 
    Note over Browser: New request GET
    Browser->>Server: Fetches for all these files again
    deactivate Browser 

    
    activate Server
    Note over Server: Send: notes.html
    Server-->>Browser: .html file tells the browser what information to display and its structure
    deactivate Server

    activate Browser 
    Note over Browser: GET: main.css 
    Browser->>Server: 
    deactivate Browser 
    Note over Server: Send: main.css 
    Server-->>Browser: .css file tells the browser how to style the information

    activate Browser 
    Note over Browser: GET: main.js 
    Browser->>Server: 
    deactivate Browser 
    Note over Server: Send: main.js 
    Server-->>Browser: Browser runs the JavaScript code which retrieves the JSON file from server

    activate Browser 
    Note over Browser: GET: data.json 
    Browser->Server: 
    deactivate Browser 
    
   

 
 Note over Browser, Server: In this process a new page is constructed by the server based on the previous template, full reload page needed

